# Generated by Django 2.2.6 on 2019-10-16 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='module_manager.ModuleName')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('h', models.IntegerField(default=0)),
                ('w', models.IntegerField(default=0)),
                ('isResizable', models.BooleanField(default=True)),
                ('isDraggable', models.BooleanField(default=True)),
                ('isStatic', models.BooleanField(default=False)),
                ('belongsToList', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='module_manager.ModuleList')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='module_manager.ModuleName')),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('modules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_manager.ModuleList')),
            ],
        ),
    ]
