# Generated by Django 2.2.6 on 2019-10-18 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layout',
            name='modules',
        ),
        migrations.RemoveField(
            model_name='module',
            name='belongsToList',
        ),
        migrations.AddField(
            model_name='module',
            name='belongsToLayout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='module_manager.Layout'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ModuleList',
        ),
    ]
