# Generated by Django 2.2.6 on 2019-11-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_manager', '0002_auto_20191017_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='isStatic',
            new_name='active',
        ),
        migrations.AddField(
            model_name='module',
            name='isMinimized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='static',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modulename',
            name='icon',
            field=models.CharField(default='cellphone-link', max_length=50),
        ),
    ]
